const ApifyClient = require('apify-client')
const apifyClient = new ApifyClient({
  userId: process.env.APIFY_USER_ID,
  token: process.env.APIFY_TOKEN
})
const lib = require('./lib')

let masaajid = [
  './lib/al-hira-community-center-wooddale',
  './lib/aqsa-community-center-plainfield',
  './lib/at-takaful-islamic-society-chicago',
  './lib/batavia-islamic-center',
  './lib/chicago-mosque',
  './lib/dar-us-sunnah-evanston',
  './lib/fox-valley-muslim-community-center',
  './lib/icc-des-plaines',
  './lib/icci-chicago',
  './lib/islamic-center-of-naperville',
  './lib/islamic-center-of-oakbrook-terrace',
  './lib/islamic-center-of-romeoville',
  './lib/islamic-center-of-western-suburbs',
  './lib/islamic-center-of-wheaton',
  './lib/islamic-foundation-of-southwest-suburbs',
  './lib/islamic-foundation-of-villa-park',
  './lib/isns-rolling-meadows',
  './lib/madani-masjid-westmont',
  './lib/makki-masjid-chicago',
  './lib/masjid-al-huda-schaumburg',
  './lib/masjid-al-mustafa-westmont',
  './lib/masjid-darussalam',
  './lib/masjid-haqq-lombard',
  './lib/masjid-ul-islam-elgin',
  './lib/masjid-uthman-lombard',
  './lib/mcc-chicago',
  './lib/mecca-center',
  './lib/mosque-foundation-bridgeview',
  './lib/muslim-association-of-bolingbrook',
  './lib/muslim-society-inc-bloomingdale',
  './lib/prayer-center-of-orland-park'
]

const main = async () => {
  // setup crawler template

  const crawlerId = 'praytime-autogenerated'
  const crawlerSettings = { customId: crawlerId }

  try {
  /* const crawler = */ await apifyClient.crawlers.createCrawler({ settings: crawlerSettings })
  } catch (err) {
    if (err.message !== 'Custom ID must be unique') {
      throw err
    }
    // crawler already exists
  }

  for (const masjid of masaajid) {
    try {
      console.error('starting %s', masjid)

      const masjidLib = require(masjid)

      let results = {}
      if (masjidLib.apifySettings) {
        // run an apify crawler
        results = await lib.getPagefunctionResults(apifyClient, crawlerId, masjidLib.apifySettings)
      } else if (masjidLib.run) {
        // generic run function
        results = await masjidLib.run()
      } else if (masjidLib.results) {
        // static results, nothing to execute
        results = masjidLib.results
      }

      results.forEach((r) => {
        console.log('%j', r)
      })
    } catch (err) {
      console.error('caught error:' + err)
      console.trace()
    }
  }
}

const argv = process.argv.slice(2)

if (argv.length > 0) {
  masaajid = argv
}

main()
