#!/usr/bin/env bash
# populate new masjid crawler, rebuild index and add to git

set -euf -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$SCRIPT_DIR/.."

# shellcheck source=common.sh
. "${PROJECT_DIR}/script/common.sh"

trap exiterr EXIT

# rebuild index
LIBDIR="$PROJECT_DIR/lib/US"
OUTFILE="$LIBDIR/index.js"

cd "$PROJECT_DIR"
{
    echo "// automatically generated by $(basename "${BASH_SOURCE[0]}")"
    echo "exports.masaajid = ["
    find ./lib/US -mindepth 2 -type f -name index.js -printf "  '%p',\n" | sort
    echo "]"
} | standard --fix --stdin > "$OUTFILE"

git add --intent-to-add "$LIBDIR"

trap - EXIT
